# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc 'Runs unit tests'
  lane :unit_tests do
    test scheme:'BeeTests'
  end

  desc "Runs UI tests"
  lane :ui_tests do
    test scheme:'BeeUITests'
  end

  desc "Runs tests for the given scheme"
  lane :test do |options|
    scheme = options[:scheme]
    scan(
      scheme: 'Bee',
      scheme: scheme,
      project: 'Bee.xcodeproj',
      device: 'iPhone 11',
      reset_simulator: true,
      code_coverage: true,
      suppress_xcode_output: true,
      output_types: 'junit,html',
      output_files: 'junit.xml, report.html',
    )
  end
end
