name: "CI"
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Bundle Install
        run: |
          bundle config path vendor/bundle
          bundle install --without=documentation --jobs 4 --retry 3
      
      - name: Unit Tests
        run: bundle exec fastlane unit_tests
        env:
          destination: $
          DEVELOPER_DIR: '/Applications/Xcode_12.app/Contents/Developer'
      
      - name: UI Tests
        run: bundle exec fastlane ui_tests
        env:
          destination: $
          DEVELOPER_DIR: '/Applications/Xcode_12.app/Contents/Developer'